server:
  port: 5000
  # ssl:
  #   enabled: true
  #   key-store: src/main/resources/keystore.p12
  #   key-store-password: "spring1234"
  #   key-store-type: PKCS12
  #   key-alias: bns-ssl

spring:
  application:
    name: boards
  datasource:
    # url: jdbc:mariadb://10.12.9.4:3307/java_board
    url: jdbc:mariadb://127.0.0.1:3307/java_board
    username: SpringUSER
    password: Spring1234
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
