server:
  port: 5001

spring:
  application:
    name: boards
  datasource:
    url: jdbc:mariadb://HOST_IP:HOST_PORT/DB_NANE
    username: DB_USER
    password: DB_PW
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
